### ISSUE TITLE
Function request

### ISSUE THREAD

**Issue by ButtCrackBob** [ab0oo/javAPRSlib#6]
I was unable to make a pull request. Please add the following function to the Position class. This will return the Forward Azimuth between to points on a sphere.

    /**
     * Returns Azimuth between two points as measured clockwise from true North
     * and vary from 0° to 360°.
     * <p>
     * This function returns the initial bearing (sometimes referred to as forward azimuth)
     * which if followed in a straight line along a great-circle arc will take you from the
     * start point to the end point.
     * </p>
     * @param position2 end position
     * @return bearing in degrees
     */
    public float direction(Position position2) {
        double Lat1 = Math.toRadians(position2.getLatitude());
        double Lon1 = position2.getLongitude();
        double Lat2 = Math.toRadians(getLatitude());
        double Lon2 = getLongitude();
        double dLon = Math.toRadians(Lon2 - Lon1);
        double y = Math.sin(dLon) * Math.cos(Lat2);
        double x = Math.cos(Lat1) * Math.sin(Lat2) - Math.sin(Lat1) * Math.cos(Lat2) * Math.cos(dLon);
        return (float) ((Math.toDegrees(Math.atan2(y, x)) + 360) % 360);
    }

**Comment by ge0rg** [comment]
Hey Bob, thanks for bringing this up. Could you also write a comment on how this works (ideally javadoc)?

I'm not deep enough into the math to actually verify the code, so it would be great to at least have the expectations documented (e.g. "@return forward azimuth in degrees (0..360)").

**Comment by ButtCrackBob** [comment]
/**
 * Returns Azimuth between two points as measured clockwise from North
 * and vary from 0° to 360°.
 * <p>
 * This function returns the initial bearing (sometimes referred to as
forward azimuth)
 * which if followed in a straight line along a great-circle arc will
take you from the
 * start point to the end point.
 * </p>
 * @param position2 end position
 * @return bearing in degrees
 */
public float direction(Position position2) {
    double Lat1 = Math.toRadians(position2.getLatitude());
    double Lon1 = position2.getLongitude();
    double Lat2 = Math.toRadians(getLatitude());
    double Lon2 = getLongitude();
    double dLon = Math.toRadians(Lon2 - Lon1);
    double y = Math.sin(dLon) * Math.cos(Lat2);
    double x = Math.cos(Lat1) * Math.sin(Lat2) - Math.sin(Lat1) *
Math.cos(Lat2) * Math.cos(dLon);
    return (float) ((Math.toDegrees(Math.atan2(y, x)) + 360) % 360);
}
